version: "3.8"
services:
  db:
    container_name: bookservice_db
    image: postgres:13.5
    restart: always
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
  server:
    build: ./
    container_name: bookservice_server
    ports:
      - "3000:3000"
